### ISSUE TITLE
Affiliation to the Haskell Foundation

### ISSUE THREAD

**Issue by Kleidukos** [haskell-cryptography/governance#3]
In order to reach our goals and fulfil our mission, we should affiliate with the Haskell Foundation. 

@cdornan @kozross @axman6 @jmcardon Let us vote, please comment with your explicit approval please.

**Comment by Kleidukos** [comment]
I vote yes

**Comment by kozross** [comment]
I vote yes.

**Comment by cdornan** [comment]
I vote yes

**Comment by ghost** [comment]
I (on behalf of myself @axman6) also vote yes.

**Comment by jmcardon** [comment]
I vote yes

**Comment by Kleidukos** [comment]
Perfect, the vote is closed. Thank you everyone.
